language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source

script: phpunit --bootstrap=vendor/autoload.php --colors tests

cache:
    directories:
        - vendor
